name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Create Firebase config
        run: |
         echo 'if (typeof firebase !== "undefined" && !firebase.apps.length) {
      const firebaseConfig = ${{ secrets.FIREBASE_CONFIG}};
      firebase.initializeApp(firebaseConfig);
      console.log("Firebase initialized with production config");
    }' > ./src/firebaseConfig.js
      
      # Add your build steps here
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: build
